var indices={flat:57585,natural:57593,flat_line:58176,natural_line:58182,punctum:57603,diamond:57619,virga:57635,v:57635,leftVirga:57651,quilisma:57667,w:57667,bottomPartPodatus:57683,topPartPodatus:57699,podatus:[null,57715,57731,57748,57763],o:57779,O:57795,dimaond_tilde:57811,gt:57827,lt:57843,upper_tilde:57859,lower_tilde:57875,porrectus:[null,57891,57907,57923,57939],r:57971,s:57987,custos:58019,dot:58035,apos:58050,ictus:58050,underscore:58066,underscore_longer:58082,clivis:[null,58115,58131,
58147,58163],accent_above_staff:58188,connecting_lines:[59139,59155,59171,59187],decorative_lines:[59203,59219,59235,59251,59267]},staffheight=60,spaceheight=staffheight/4,notewidth=staffheight/6,spaceBetweenNeumes=notewidth,fontsize=spaceheight*1.5,spaceWidth=fontsize/2,staffoffset=Math.ceil(staffheight*1.4),svgns="http://www.w3.org/2000/svg",xlinkns="http://www.w3.org/1999/xlink",styleCaeciliae="font-family: 'Caeciliae Staffless'; font-size:"+staffheight+";",styleGoudy="font-family: 'OFL Sorts Mill Goudy TT'; font-size: "+
fontsize+";",svg,textElem,codea="a".charCodeAt(0),codem=codea+12,codeA="A".charCodeAt(0),codeM=codeA+12,regexOuter=/((([^\(\r\n]+)($|\())|\()([^\)]*)($|\))([ \t]*)/g,regexTag=/<(\/)?(b|i|sc)>/i,regexInner=/(?:[!\/ ,;:`]+|[^\)!\/ ,;:`\[]+)(?:\[[^\]]*(?:$|\]))?/g,oldRegexTones=/([\/ ,;:`]+)|([A-M][^a-mA-M]*)|[a-m][^a-mA-M]*/g,tagStyle={b:"font-weight:bold;",i:"font-style:italic;",sc:"font-variant:small-caps"},regexTones=/([\/ ,;:`]+)|([cfCF][1-4])|(?:(-)?(?:([A-M])|([a-m]))(?:(')|(\.{1,2})|(_{1,4})|(([Vv]{1,3})|(s{1,3})|((<)|(>)|(~))|(w)|(o)|(O)|((x)|(y))|(q)|((R)|(r0)|(r(?![1-5])))|(r[1-5])))*|(z0))|\[([^\]]*)(?:\]|$)/g,
rtg={whitespace:1,keychange:2,initioDebilis:3,toneUpper:4,toneLower:5,ictus:6,dot:7,episema:8,noteType:9,virga:10,stropha:11,liquescentia:12,diminutiveLiquescentia:15,ascendingLiquescentia:13,descendingLiquescentia:14,quilisma:16,oriscus:17,oriscusReverse:18,accidental:19,flat:20,natural:21,q:22,punctumCavum:26,lineaPunctum:24,lineaPunctumCavum:25,rNumber:27,custos:28,bracketed:29},regexVowel=/(?:[cgq]u(?=[aeiouy\u00e1\u00e9\u00eb\u00ed\u00f3\u00fa\u00fd\u00e6\u0153])|[iy])?([a\u00e1]u|[ao][e\u00e9]?|[aeiouy\u00e1\u00e9\u00eb\u00ed\u00f3\u00fa\u00fd\u00e6\u0153])/gi,
transforms=[["/"," ",",",";",":","`",""],["'","_","+",";","|",",",""],[/\//g,/ /g,/,/g,/;/g,/:/g,/`/g,/!/g]],abcs={},defs=null,defText=null,defChant=null,masks=[];function updatePreview(j){var d=textElem;textElem=getChant(j);svg.replaceChild(textElem,d);svg.setAttribute("height",textElem.getBBox().height)}
function updateChant(j,d){var b=d.childNodes,g=null;for(i=b.length-1;i>=0;--i)if(b[i].tagName=="g"){g=b[i];break}if(g){b=getChant(j);d.replaceChild(b,g);d.setAttribute("height",b.getBBox().height)}}function make(j){return document.createElementNS(svgns,j)}
function getChant(j){var d,b=0,g=make("g");regexOuter.lastIndex=0;g.setAttribute("transform","translate(0,"+staffoffset+")");g.setAttribute("style",styleCaeciliae);var h=0,m=0,a,k,c=null,e=make("text");e.setAttribute("style",styleGoudy);var f,l=3,n=0,o=[0],u=svg.width.baseVal.value,v=null,z=false,s,y=[],A=[],r="";for(addStaff(g,o[n],n,null);d=regexOuter.exec(j);){if(d[5])v=getChantFragment(d[5]);var w=d[5]?document.getElementById(d[5]).getComputedTextLength():0,p=d[3]||d[7];if(d[3]&&d[7])p+=d[7];
var q=0;if(p){for(p=p.trimLeft().replace("\r\n"," ").replace("\n"," ");t=A.pop();)y.splice(y.indexOf(t),1);for(;r=regexTag.exec(p);){if(r[1]!="/")y.indexOf(r[2])<0&&y.push(r[2]);else A.indexOf(r[2])<0&&A.push(r[2]);var x=r.index+r[0].length;p=r.index==0?p.substring(r[0].length):p.substring(0,r.index)+p.substring(x,p.length)}r="";for(var C in y)r+=tagStyle[y[C]];defText.setAttribute("style",styleGoudy+r);defText.firstChild.data="."+p+".";a=defText.getSubStringLength(1,p.length);regexVowel.lastIndex=
0;(vowel=regexVowel.exec(p))||(vowel={index:0,"0":p,"1":p});defText.firstChild.data=p.substring(0,vowel.index+vowel[0].length);try{var B=vowel.index+vowel[0].length-vowel[1].length;q-=defText.getSubStringLength(0,B);q-=defText.getSubStringLength(B,vowel[1].length)/2}catch(D){}q+=notewidth/2}else a=0;m+=q;if(w>0&&h<m)h=m;x=h+a;w=h+w+spaceBetweenNeumes-q;f=Math.max(x,w);if(a==0)x=w;if(f>=u-spaceBetweenNeumes){z=true;l=3-l;l=l<=0?0:l*spaceheight/2;a=Math.ceil(0.1*staffheight+fontsize+l);e.setAttribute("y",
a);g.appendChild(e);e=make("text");e.setAttribute("style",styleGoudy);l=3;o.push(staffoffset+a+o[n++]);e.setAttribute("transform","translate(0,"+o[n]+")");curStaff=addStaff(g,o[n],n,null);x-=h;w-=h;h=0}if(d[5]){if(z){addCustos(g,v.ftone,o[n-1]);z=false}if(v.mask){k=make("use");k.setAttributeNS(xlinkns,"href","#"+v.mask);k.setAttribute("x",h);k.setAttribute("y",o[n]);masks[n].firstChild.appendChild(k)}else k=null;l=Math.min(l,v.ltone);a=make("use");a.setAttributeNS(xlinkns,"href","#"+d[5]);a.setAttribute("x",
h);a.setAttribute("y",o[n]);g.appendChild(a)}else a=k=null;if(d[3]||d[7]){f=c;c=make("tspan");m=h;if(a)if(q>0)m+=q;else{a.setAttribute("transform","translate("+-q+")");k&&k.setAttribute("transform","translate("+-q+")")}if(s&&s[3]&&!s[7]){defText.firstChild.data=f.firstChild.data;q=parseInt(f.getAttribute("x"),10);s=q+defText.getComputedTextLength();if(s<m){f.firstChild.data+="-";defText.firstChild.data+="-";s=q+defText.getComputedTextLength();if(s>m){q=s-m;m=s;a&&a.setAttribute("x",h+q);x+=q;w+=q}}}c.setAttribute("x",
m);c.setAttribute("style",r);h=x;m=w;c.appendChild(document.createTextNode(p||""));e.appendChild(c)}else if(a)h+=document.getElementById(d[5]).getComputedTextLength()+5;b++;s=d}l=3-l;l=l<=0?0:l*spaceheight/2;e.setAttribute("y",Math.ceil(0.1*staffheight+fontsize+l));g.appendChild(e);return g}
function addCustos(j,d,b){var g=make("text");g.setAttribute("style",defChant.getAttribute("style"));g.setAttribute("x",svg.width.baseVal.value-staffheight/15);g.setAttribute("y",b);g.appendChild(document.createTextNode(String.fromCharCode(indices.custos+d)));j.appendChild(g)}
function getChantFragment(j){if(abcs[j]!=undefined)return abcs[j];var d=undefined;if(j.indexOf("r")>-1){d=j.replace(/r/g,"!");getChantFragment(d)}var b=make("text"),g=3,h=0,m=null;b.setAttribute("id",j);var a="",k=make("tspan"),c;c=0;var e=57603,f;for(regexInner.lastMatch=0;f=regexInner.exec(j);){var l=[];c=0;a="";chant=f[0];for(regexTones.lastMatch=0;cmatch=regexTones.exec(chant);)if(!cmatch[rtg.bracketed]){tone=cmatch[0];if(cmatch[rtg.whitespace]){for(f=0;f<transforms[0].length;++f)tone=tone.replace(transforms[2][f],
transforms[1][f]);a+=tone}else{var n=tone.charCodeAt(0)-(cmatch[rtg.toneUpper]?codeA:codea);if(tone.length==1){g=Math.min(g,n);h=Math.max(h,n);m=m||n}l.push({match:cmatch,index:n,relativeTone:n-c,modifiers:tone.length==1?null:tone.substring(1),diamond:cmatch[rtg.toneUpper]?true:false});c=n}}for(f=0;f<l.length;++f){var o=1;tone=l[f];c=l.length>f+1?l[f+1]:null;var u=l.length>f+2?l[f+2]:null,v=f>0?l[f-1]:null;e=indices.punctum;if(tone.diamond){e=57619;u=Math.abs(tone.relativeTone);if(v&&v.diamond&&u==
1||u==2){if(a.length>0){k.appendChild(document.createTextNode(a));b.appendChild(k);k=make("tspan");a=""}k.setAttribute("dx",staffheight/(u==1?-20:30))}}else if(tone.modifiers){if((tone.index==2||tone.index==5)&&tone.modifiers[0].match(/[1-4]/)){o=0;if(a.length>0){k.appendChild(document.createTextNode(a));b.appendChild(k);k=make("tspan");a=""}else o=parseInt(k.getAttribute("dy")||0,10);line=parseInt(tone.modifiers[0],10);e=0;if(tone.index==2){c="d''";e=2-line}else{c="f''";e=3-line}e*=spaceheight;k.setAttribute("dy",
e+o);k.appendChild(document.createTextNode(c));b.appendChild(k);k=make("tspan");k.setAttribute("dy",-e);continue}g=Math.min(g,n);h=Math.max(h,n);m=m||n;if(tone.modifiers=="x"||tone.modifiers=="y"){o=tone.modifiers=="x"?"flat":"natural";if(tone.index%2==1){o+="_line";tone.index-=1}c=tone.index/2;c+=indices[o];if(c)a+=String.fromCharCode(c);continue}else if(indices[tone.modifiers[0]]){e=indices[tone.modifiers[0]];if(c&&c.relativeTone==1&&tone.modifiers=="w"){a+=String.fromCharCode(e+tone.index);++f;
e=indices.topPartPodatus;tone=c}}}else if(c&&!c.diamond)if(c.relativeTone>0&&c.relativeTone<=4){e=indices.podatus[c.relativeTone];o=2;++f}else if(c.relativeTone<0&&c.relativeTone>=-4){if(u&&u.relativeTone==1){e=indices.porrectus[-c.relativeTone];a+=String.fromCharCode(e+tone.index);e=indices.topPartPodatus;tone=u;o=3;++f}else{e=indices.clivis[-c.relativeTone];o=2}++f}a+=String.fromCharCode(e+tone.index);if(tone.match[rtg.ictus])a+=String.fromCharCode(indices.ictus+tone.index);if(e=tone.match[rtg.dot])e=
e.length;else if(o==2)e=(e=c.match[rtg.dot])?e.length:0;else e=0;if(e>1&&c){o=Math.min(c.index,tone.index);c=Math.max(c.index,tone.index);o%2==1&&--o;a+=String.fromCharCode(indices.dot+o);a+=String.fromCharCode(indices.dot+c)}else if(e>0)a+=o==2?String.fromCharCode(indices.dot+c.index):String.fromCharCode(indices.dot+tone.index)}if(a.length>0){k.appendChild(document.createTextNode(a));b.appendChild(k)}}defs.appendChild(b);return abcs[j]={ltone:g,htone:h,ftone:m,mask:d}}
function addStaff(j,d,b,g){var h="staffmask"+b;if(masks[b])for(b=masks[b].firstChild;b.childElementCount>1;)b.removeChild(b.childNodes[1]);else{b=masks[b]=make("mask");var m=make("g");m.setAttribute("style",styleCaeciliae);b.appendChild(m);var a=make("rect");a.setAttribute("y",d+1-staffheight);a.setAttribute("width","10000");a.setAttribute("height",staffheight);a.setAttribute("fill","white");m.appendChild(a);b.setAttribute("id",h);defs.appendChild(b)}b=make("g");b.setAttribute("mask","url(#"+h+")");
h=make("use");h.setAttributeNS(xlinkns,"href","#staff");if(!g)g=svg.width.baseVal.value;h.setAttribute("transform","translate(0, "+d+") scale("+g+",1)");b.appendChild(h);j.appendChild(b);return h}
$(function(){var j=$("#tbl");if(j)for(var d=57568;d<65535;d+=16){var b=document.createElement("row"),g=document.createElement("td"),h=document.createElement("td");g.innerText="0x"+d.toString(16);for(var m="",a=0;a<16;++a)m+=String.fromCharCode(d+a)+"_";h.innerText=m;h.className="caeciliae";b.appendChild(g);b.appendChild(h);j.append(b)}svg=document.createElementNS(svgns,"svg");svg.setAttribute("style","width:100%");j=document.createElementNS(svgns,"style");j.setAttribute("type","text/css");j.appendChild(document.createTextNode("@font-face {font-family: 'Caeciliae Staffless'; font-weight: normal; font-style: normal;src: local(Caeciliae Staffless); src:url(http://jgabc.googlecode.com/svn/trunk/Caeciliae-Staffless.ttf) format(opentype)}@font-face {font-family: 'Caeciliae-staffless'; font-weight: normal; font-style: normal; src: local(Caeciliae Staffless)}@font-face {font-family: 'OFL Sorts Mill Goudy TT'; font-style: italic; font-weight: normal; src: local('OFL Sorts Mill Goudy Italic TT'), local('OFLGoudyStMTT-Italic'), url('http://themes.googleusercontent.com/font?kit=4zlbkWdiblhTyAxV3yYOK1Map0k-03pf3IKr-TpLv1-glnMp3_3A8V8Ai8YosRtX') format('truetype');}@font-face {font-family: 'OFL Sorts Mill Goudy TT'; font-style: normal; font-weight: normal; src: local('OFL Sorts Mill Goudy TT'), local('OFLGoudyStMTT'), url('http://themes.googleusercontent.com/font?kit=9ZZVVBRCceNnPBXqWLH8IBaCi8XR2Wndwbau3-eaE1g') format('truetype');}"));
svg.appendChild(j);defs=document.createElementNS(svgns,"defs");defText=make("text");defText.setAttribute("style",styleGoudy);defText.appendChild(document.createTextNode(""));defs.appendChild(defText);defChant=make("text");defChant.setAttribute("style",styleCaeciliae);defChant.appendChild(document.createTextNode("p"));defs.appendChild(defChant);j=document.createElementNS(svgns,"g");j.setAttribute("id","staff");b=staffheight*16/1E3;d=document.createElementNS(svgns,"path");b="h1v"+b+"h-1zm0 -"+spaceheight;
d.setAttribute("d","M0 0"+b+b+b+b);j.appendChild(d);defs.appendChild(j);svg.appendChild(defs);textElem=document.createElementNS(svgns,"g");svg.appendChild(textElem);$("#chant-preview").append(svg);var k=$(".jgabc");k.each(function(e,f){$(svg).clone().appendTo(f)});$("#editor").keyup(function(){updateChant($("#editor")[0].value,svg)});var c=function(){if(svg.width.baseVal.value==0)setTimeout(c,100);else{updateChant($("#editor")[0].value,svg);k.each(function(e,f){var l=f.childNodes,n=null;for(a=l.length-
1;a>=0;--a)if(l[a].tagName=="svg"){n=l[a];break}n&&updateChant(f.innerText,n)})}};setTimeout(c,100)});window.updatePreview=updatePreview;window.updateChant=updateChant;