var massOrdinary = [{
  season:"In Paschal Time",
  name:"Lux et origo",
  kyrie:{id: 1143,name: "Kyrie I"},
  gloria:{id: 2980,name: "Gloria I"},
  sanctus:{id: 300,name: "Sanctus I"},
  agnus:{id: 2977,name: "Agnus I"},
  ite:[{id: 2987,name: "Ite I"},
       {id: 2988,name: "Ite I (within octave of Easter)", "feast":/^(Quad6s|Pasc0\w?)$/}]
},{season:"For 1st class feasts - 1.",
  name:"Kyrie fons bonitatis",
  kyrie:{id: 309,name: "Kyrie II"},
  gloria:{id: 862,name: "Gloria II"},
  sanctus:{id: 1279,name: "Sanctus II"},
  agnus:{id: 555,name: "Agnus II"},
  benedicamus:{id: 612,name: "Benedicamus II"},
  ite:[{id: 804,name: "Ite IIb"}, // more usually
    {id: 1280,name: "Ite IIa"}]
},{season:"For 1st class feasts - 2.",
  name:"Kyrie Deus sempiterne",
  kyrie:{id: 825,name: "Kyrie III"},
  gloria:{id: 71,name: "Gloria III"},
  sanctus:{id: 566,name: "Sanctus III"},
  agnus:{id: 578,name: "Agnus III"},
  benedicamus:{id: 612,name: "Benedicamus II"},
  ite:[{id: 1280,name: "Ite IIa"},
    {id: 804,name: "Ite IIb"}]
},{season:"For 2nd class feasts - 1.",
  name:"Cunctipotens Genitor Deus",
  kyrie:{id: 1061,name: "Kyrie IV"},
  gloria:{id: 2978,name: "Gloria IV"},
  sanctus:{id: 2518,name: "Sanctus IV"},
  agnus:{id: 264,name: "Agnus IV"},
  benedicamus:{id: 2856,name: "Benedicamus IV"},
  ite:{id: 353,name: "Ite IV"}
},{season:"For 2nd class feasts - 2.",
  name:"Kyrie magnæ Deus potentiæ",
  kyrie:{id: 474,name: "Kyrie V"},
  gloria:{id: 337,name: "Gloria V"},
  sanctus:{id: 2984,name: "Sanctus V"},
  agnus:{id: 1241,name: "Agnus V"},
  ite:{id: 1006,name: "Ite V"}
},{season:"For 2nd class feasts - 3.",
  name:"Kyrie Rex Genitor",
  kyrie:{id: 2903,name: "Kyrie VI"},
  gloria:{id: 321,name: "Gloria VI"},
  sanctus:{id: 431,name: "Sanctus VI"},
  agnus:{id: 387,name: "Agnus VI"},
  ite:{id: 1160,name: "Ite VI"}
},{season:"For 2nd class feasts - 4.",
  name:"Kyrie Rex splendens",
  kyrie:{id: 1262,name: "Kyrie VII"},
  gloria:{id: 721,name: "Gloria VII"},
  sanctus:{id: 1089,name: "Sanctus VII"},
  agnus:{id: 2985,name: "Agnus VII"},
  ite:{id: 31,name: "Ite VII"}
},{season:"For 2nd class feasts - 5.",
  name:"De Angelis",
  kyrie:{id: 1184,name: "Kyrie VIII"},
  gloria:{id: 961,name: "Gloria VIII"},
  sanctus:{id: 1384,name: "Sanctus VIII"},
  agnus:{id: 2760,name: "Agnus VIII"},
  benedicamus:{id: 2901,name: "Benedicamus VIII"},
  ite:{id: 832,name: "Ite VIII"}
},{season:"For feasts of the Blessed Virgin - 1.",
  name:"Cum jubilo",
  kyrie:{id: 2976,name: "Kyrie IX"},
  gloria:{id: 2771,name: "Gloria IX"},
  sanctus:{id: 587,name: "Sanctus IX"},
  agnus:{id: 707,name: "Agnus IX"},
  benedicamus:{id: 2902,name: "Benedicamus IX"},
  ite:{id: 2989,name: "Ite IX"}
},{season:"For feasts of the Blessed Virgin - 2.",
  name:"Alme Pater",
  kyrie:{id: 795,name: "Kyrie X"},
  gloria:{id: 1204,name: "Gloria X"},
  sanctus:{id: 2770,name: "Sanctus X"},
  agnus:{id: 2981,name: "Agnus X"},
  benedicamus:{id: 2902,name: "Benedicamus IX"},
  ite:{id: 2989,name: "Ite IX"}
},{season:"For Sundays throughout the year",
  name:"Orbis factor",
  kyrie:[{id: 2982,name: "Kyrie XI"},
    {id: 2604,name: "Kyrie (ad lib.) X. - Orbis Factor"}],
  gloria:{id: 303,name: "Gloria XI"},
  sanctus:{id: 1106,name: "Sanctus XI"},
  agnus:{id: 1243,name: "Agnus XI"},
  benedicamus:{id: 2920,name: "Benedicamus XI"},
  ite:{id: 856,name: "Ite XI"}
},{season:"For 3rd class feasts - 1.",
  name:"Pater cuncta",
  kyrie:{id: 2068,name: "Kyrie XII"},
  gloria:{id: 2114,name: "Gloria XII"},
  sanctus:{id: 1062,name: "Sanctus XII"},
  agnus:{id: 759,name: "Agnus XII"},
  ite:{id: 37,name: "Ite XII"}
},{season:"For 3rd class feasts - 2.",
  name:"Stelliferi Conditor orbis",
  kyrie:{id: 137,name: "Kyrie XIII"},
  gloria:{id: 2107,name: "Gloria XIII"},
  sanctus:{id: 1067,name: "Sanctus XIII"},
  agnus:{id: 2886,name: "Agnus XIII"},
  benedicamus:{id: 2952,name: "Benedicamus XIII"},
  ite:{id: 878,name: "Ite XIII"}
},{season:"For 3rd class feasts - 3.",
  name:"Jesu Redemptor",
  kyrie:{id: 441,name: "Kyrie XIV"},
  gloria:{id: 908,name: "Gloria XIV"},
  sanctus:{id: 2979,name: "Sanctus XIV"},
  agnus:{id: 2076,name: "Agnus XIV"},
  ite:{id: 2986,name: "Ite XIV"}
},{season:"For commemorations and ferias of the Christmas season",
  name:"Dominator Deus",
  kyrie:{id: 393,name: "Kyrie XV"},
  gloria:{id: 2975,name: "Gloria XV"},
  sanctus:{id: 386,name: "Sanctus XV"},
  agnus:{id: 959,name: "Agnus XV"},
  ite:{id: 620,name: "Ite XV"}
},{season:"For ferias throughout the year",
  name:"",
  kyrie:{id: 545,name: "Kyrie XVI"},
  sanctus:{id: 2990,name: "Sanctus XVI"},
  agnus:{id: 1336,name: "Agnus XVI"},
  benedicamus:{id: 2227,name: "Benedicamus (ad lib.)"},
},{season:"For the Sundays of Advent and Lent",
  name:"",
  kyrie:[{id: 272,name: "Kyrie XVII A"},
    {id: 2614,name: "Kyrie (ad lib.) XI. - Kyrie Salve"},
    {id: 168,name: "Kyrie XVII C"}],
  sanctus:{id: 871,name: "Sanctus XVII"},
  agnus:{id: 1137,name: "Agnus XVII"},
  ite:{id: 620,name: "Ite XV"},
  benedicamus:[{id:543,name: "Benedicamus XVII A"},
    {id:3015,name: "Benedicamus XVII C"}]
},{season:"For the ferias of Advent and Lent (as well as for Vigils, Ember Days, and Rogation Days",
  name:"Deus Genitor alme",
  kyrie:{id: 2522,name: "Kyrie XVIII"},
  sanctus:{id: 298,name: "Sanctus XVIII"},
  agnus:{id: 2412,name: "Agnus XVIII"},
  benedicamus:[{id: 612,name: "Benedicamus II"},
    {id: 2227,name: "Benedicamus (ad lib.)"}],
  ite:{id: 620,name: "Ite XV"}
},{season:"Missa Sancti Hildegardis",
  kyrie:{id: 7957,name: "Kyrie M. S. Hildegard."},
  gloria:{id: 7958,name: "Gloria M. S. Hildegard."},
  sanctus:{id: 7959,name: "Sanctus M. S. Hildegard."},
  agnus:{id: 7960,name: "Agnus M. S. Hildegard."},
  ite:{id: 7961,name: "Ite M. S. Hildegard."}
},{season:"Missa Regia I",
  kyrie:{id: 7995,name: "Kyrie M. R. I"},
  gloria:{id: 7996,name: "Gloria M. R. I"},
  credo:{id: 7997,name: "Credo M. R. I"},
  sanctus:{id: 7998,name: "Sanctus M. R. I"},
  agnus:{id: 7937,name: "Agnus M. R. I"},
  ite:{id: 8000,name: "Ite M. R. I"}
},{season:"Missa pro defunctis",
  kyrie:{id: 541,name: "Kyrie eleison (in Miss. def.)"},
  sanctus:{id: 298,name: "Sanctus XVIII"},
  agnus:{id: 2118,name: "Agnus Dei (in Miss. def.)"},
  benedicamus:{id: 823,name: "Requiescant in pace"}
}];

var ordinaryAdLib = {
asperges:[{id: 497,name: "Asperges me"},
  {id: 905,name: "Asperges me (ad lib.) I."},
  {id: 142,name: "Asperges me (ad lib.) II."},
  {id: 958,name: "Vidi aquam"},
  {id: 10298,name: "Vidi aquam (ad lib.)"},
  {id: 10358,name: "Vidi aquam (B)"}],
kyrie:[{id: 2993,name: "Kyrie (ad lib.) I. - Clemens Rector"},
  {id: 2021,name: "Kyrie (ad lib.) II. - Summe Deus"},
  {id: 2237,name: "Kyrie (ad lib.) III. - Rector cosmi pie"},
  {id: 2254,name: "Kyrie (ad lib.) IV. - Kyrie altissime"},
  {id: 2261,name: "Kyrie (ad lib.) V. - Conditor Kyrie omnium"},
  {id: 2269,name: "Kyrie (ad lib.) VI. - Te Christe Rex supplices"},
  {id: 2363,name: "Kyrie (ad lib.) VII. - Splendor aeterne"},
  {id: 2468,name: "Kyrie (ad lib.) VIII. - Firmator sancte"},
  {id: 2599,name: "Kyrie (ad lib.) IX. - O Pater excelse"},
  {id: 2604,name: "Kyrie (ad lib.) X. - Orbis Factor"},
  {id: 2614,name: "Kyrie (ad lib.) XI. - Kyrie Salve"}],
gloria:[{id: 2659,name: "Gloria (ad lib.) I."},
  {id: 2685,name: "Gloria (ad lib.) II."},
  {id: 2707,name: "Gloria (ad lib.) III."},
  {id: 2749,name: "Gloria (Ambrosian)"}],
credo:[{id: 344,name: "Credo I"},
  {id: 2983,name: "Credo II"},
  {id: 749,name: "Credo III"},
  {id: 678,name: "Credo IV"},
  {id: 955,name: "Credo V"},
  {id: 2934,name: "Credo VI"},
  {id: 7915,name: "Credo VII"},
  {id: 7997,name: "Credo M.R. I"}],
preface:[{id: 7674,name: "Solemn Tone"},
  {id: 7675,name: "Ferial Tone"},
  {id: 7676,name: "Most Solemn Tone"}
],
sanctus:[{id: 2816,name: "Sanctus (ad lib.) I."},
  {id: 2820,name: "Sanctus (ad lib.) II."},
  {id: 2849,name: "Sanctus (ad lib.) III."}],
agnus:[{id: 2850,name: "Agnus (ad lib.) I."},
  {id: 2851,name: "Agnus (ad lib.) II."}],
benedicamus:{id: 2227,name: "Benedicamus (ad lib.)"},
ite:{id: 620,name: "Ite XV"}
};
